### ISSUE TITLE
Diagnostics file path might be for different file but shows on current file

### ISSUE THREAD

**Issue by lhl2617** [nwhetsell/linter-lilypond#1]
Hi, I've not personally used your extension, but I developed the VSCode counterpart (https://marketplace.visualstudio.com/items?itemName=lhl2617.vslilypond).

Your approach for linting using regex is clean, and I will overhaul my setup to follow yours (mine is messy because I'm not very familiar with regex); however, one thing I caught was that it appears your script does not send diagnostics to the correct file. (Something I did not notice in my current version as well, will overhaul).

**Problem**:

If you use \include directives in LilyPond, LilyPond will warn you of errors in another file if the error is in that file. With the current setup, it appears that it will send it to the current file.
https://github.com/nwhetsell/linter-lilypond/blob/58effb8578fbcd4c413e0891a08e031c78b24059/lib/linter-lilypond.coffee#L53

P/S: This might be of interest: https://github.com/lhl2617/VSLilyPond-snippets

**Comment by nwhetsell** [comment]
Thanks for the report, this should be fixed in commit 5bad751d9a367d31dbb5607c1f6ddbe0af9638de, with a test added in commit 7e70e27176a5f2beea02d177143f5c4500e8f0ea.

**Comment by lhl2617** [comment]
Follow up: 
1) I noticed you turned off printed score output using --define-default=backend=null -- I was wondering if you know this produces a `-.mid` MIDI file in the cwd?
2) Does this extension support extra arguments for lilypond (e.g. custom include directories)? Because in my case, I do, and the resolving for lint errors is messy (absolute paths... where to show errors etc.).

**Comment by lhl2617** [comment]
My proposed solution for 1 in my extension is to set --output to a tmp path, and lilypond's behavior after this is to output all errors in their absolute path (for some reason!)

This makes sending the include path errors to the editors a bit cleaner... but is strange!

**Comment by nwhetsell** [comment]
> I was wondering if you know this produces a -.mid MIDI file in the cwd (if midi output is specified)

I didn’t know that, thanks for letting me know.

> Does this extension support extra arguments for the lilypond linter process (e.g. custom include directories)?

Not yet, and while I’m not sure when I might get around to adding something like this, a pull request would be welcome.

> This line in regex
https://github.com/nwhetsell/linter-lilypond/blob/05cb5ddfdb3866e9fa7ad70b33ee103fab440f48/lib/linter-lilypond.coffee#L5
might not work for absolute paths in Windows/networked directories with `:` in the path

I’m going to leave this as-is until there’s a report of something actually breaking because of it.
